name: Sync from Coding
on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次（可选）
  workflow_dispatch:       # 允许手动触发
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 拉取完整历史记录

      - name: Sync from Coding
        run: |
          # 添加 Coding 仓库为远程源
           git remote add coding "https://${{ secrets.CODING_USERNAME }}:${{ secrets.CODING_ACCESS_TOKEN }}@e.coding.net/lantiandev/lantianzhiwei/dmln.git"
          # git remote add coding "${{ secrets.CODING_REPO_URL }}"
          # https://e.coding.net/lantiandev/lantianzhiwei/dmln.git
          # 配置 Git 用户信息（与 Coding 账号无关）
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          # 拉取 Coding 代码并合并到当前分支
          git pull coding master --rebase --allow-unrelated-histories
          # 推送更新到 GitHub
          git push origin master
        # env:
        #   # 使用 Secrets 中的用户名和 Token 认证
        #   GIT_USERNAME: ${{ secrets.CODING_USERNAME }}
        #   GIT_PASSWORD: ${{ secrets.CODING_ACCESS_TOKEN }}
