name: Sync from Coding to GitHub Mirror
on:
  schedule:
    - cron: "0 * * * *"  # 每小时同步一次
  workflow_dispatch:     # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # 必需：允许推送
      pull-requests: write

    steps:
      - name: Checkout GitHub repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 必需：获取完整历史记录
          token: ${{ secrets.GH_PAT }}  # 使用具有推送权限的PAT

      - name: Configure Git Identity
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"

      - name: Sync from Coding
        run: |
          # 添加Coding远程仓库
          git remote add coding "https://${{ secrets.CODING_USERNAME }}:${{ secrets.CODING_ACCESS_TOKEN }}@e.coding.net/lantiandev/lantianzhiwei/dmln.git"
          
          # 强制从Coding拉取最新代码
          git fetch --force coding master:temp-master
          git checkout master
          git merge --allow-unrelated-histories --strategy-option theirs temp-master
          
          # 推送到GitHub镜像仓库
          git remote add mirror https://${{ secrets.GH_PAT }}@github.com/zhipeng1998/dmln-mirror.git
          git push mirror master
        env:
          GIT_ASKPASS: "echo"  # 禁用交互式密码提示
